[pytest]
markers =
    regression: Regression tests
    api: Api
    ensembl: Ensembl Client
    ncbi: NCBI Client
    uniprot: UniProt Client
    services: Services
    gene_service: Gene Services
    mutation_service: Mutation Services
    substitution: Substitution nucleotide
    deletion: Deletion nucleotide
    exon_deletion: ExonDeletion nucleotide
    insertion: Insertion nucleotide

addopts = -v --strict-markers
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*